const LENGTH_OF_ID = 24;
const PASSWORD_HASH = 10;
const SECRET = 'SECRET';
const SEVEN_DAYS = 604800000;
const STATUS_CREATED = 201;
const STATUS_OK = 200;

module.exports = {
  LENGTH_OF_ID,
  PASSWORD_HASH,
  SECRET,
  SEVEN_DAYS,
  STATUS_CREATED,
  STATUS_OK,
};
