const ERROR_VALIDATION = 400;
const ERROR_COMMON = 500;
const ERROR_NOT_FOUND = 404;
const ERROR_NOT_VALID_AUTH = 401;
const ERROR_ACCESS_DENIED = 403;
const ERROR_UNIQ_STRING_CONFLICT = 409;
const LENGTH_OF_ID = 24;

module.exports = {
  ERROR_VALIDATION,
  ERROR_COMMON,
  ERROR_NOT_FOUND,
  LENGTH_OF_ID,
  ERROR_NOT_VALID_AUTH,
  ERROR_ACCESS_DENIED,
  ERROR_UNIQ_STRING_CONFLICT,
};
